const MOVIE_GENRE_API="https://api.themoviedb.org/3/genre/movie/list?language=ru"
const MOVIE_TOKEN="eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjMDdkMWQzOTlkZDQyM2E5ZGNlZjE4NWRiMjIzMzMyNiIsInN1YiI6IjY1ZTc4NGRiNjg0MGNjMDE4Njc2NmU3NCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.pe2UUickHr1lwlBEAFdUWzWd1FaYxd97gt4t-tIcyfg"

export { MOVIE_GENRE_API, MOVIE_TOKEN }